#pragma once

/// @file http.h
/// @brief Minimal HTTP/1.1 — WebSocket upgrade handshake + REST client.
///
/// WS upgrade: build the GET Upgrade request (with a caller-supplied random
/// Sec-WebSocket-Key) and validate the 101 response. Validation of the
/// Sec-WebSocket-Accept hash is delegated to a caller-provided expected value
/// (computed via security/ws_handshake_hash.h) so this header — and all of
/// `net` — stays free of any crypto dependency.

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <limits>
#include <span>
#include <string_view>

namespace lepton::net {

// ── WebSocket upgrade ────────────────────────────────────────────────────────

/// Build the upgrade request into `dst`. `sec_key_b64` is base64 of 16 random
/// bytes generated by the caller (RFC 6455 §4.1). Returns bytes written or 0 if
/// `dst` is too small.
[[nodiscard]] inline std::size_t build_ws_upgrade(std::span<char> dst,
                                                  std::string_view host,
                                                  std::string_view path,
                                                  std::string_view sec_key_b64) noexcept {
    // Assemble by appending; bail out if we would overflow dst.
    std::size_t o = 0;
    auto put = [&](std::string_view s) noexcept -> bool {
        if (o + s.size() > dst.size()) {
            return false;
        }
        std::memcpy(dst.data() + o, s.data(), s.size());
        o += s.size();
        return true;
    };

    if (!put("GET ") || !put(path) || !put(" HTTP/1.1\r\nHost: ") || !put(host) ||
        !put("\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Key: ") ||
        !put(sec_key_b64) || !put("\r\nSec-WebSocket-Version: 13\r\n\r\n")) {
        return 0;
    }
    return o;
}

struct WsUpgradeResult {
    bool complete{false};       ///< headers fully received?
    bool accepted{false};       ///< 101 + valid Sec-WebSocket-Accept?
    std::size_t headers_len{0}; ///< bytes consumed (payload may follow)
};

namespace detail {

/// Case-insensitive check that `hay` begins with `needle`.
[[nodiscard]] inline bool istarts_with(std::string_view hay, std::string_view needle) noexcept {
    if (hay.size() < needle.size()) {
        return false;
    }
    for (std::size_t i = 0; i < needle.size(); ++i) {
        auto c1 = static_cast<unsigned char>(hay[i]);
        auto c2 = static_cast<unsigned char>(needle[i]);
        if (c1 >= 'A' && c1 <= 'Z') c1 |= 0x20;
        if (c2 >= 'A' && c2 <= 'Z') c2 |= 0x20;
        if (c1 != c2) {
            return false;
        }
    }
    return true;
}

} // namespace detail

/// Validate a (possibly partial) upgrade response. `expected_accept_b64` is
/// computed by the caller from the sent key. `complete` is false until the full
/// header block (\r\n\r\n) is present; callers keep reading until then.
[[nodiscard]] inline WsUpgradeResult validate_ws_upgrade(
    std::span<const char> resp, std::string_view expected_accept_b64) noexcept {
    WsUpgradeResult r;
    std::string_view s{resp.data(), resp.size()};

    const auto hdr_end = s.find("\r\n\r\n");
    if (hdr_end == std::string_view::npos) {
        return r;  // incomplete
    }
    r.complete = true;
    r.headers_len = hdr_end + 4;

    // Status line must be "HTTP/1.x 101 ...".
    if (!detail::istarts_with(s, "HTTP/1.")) {
        return r;
    }
    const auto sp = s.find(' ');
    if (sp == std::string_view::npos || sp + 4 > s.size()) {
        return r;
    }
    if (s.compare(sp + 1, 3, "101") != 0) {
        return r;
    }

    // Find Sec-WebSocket-Accept: <value> (case-insensitive header name).
    std::string_view headers = s.substr(0, r.headers_len);
    std::size_t pos = 0;
    while (pos < headers.size()) {
        std::size_t eol = headers.find("\r\n", pos);
        if (eol == std::string_view::npos) {
            break;
        }
        std::string_view line = headers.substr(pos, eol - pos);
        constexpr std::string_view kName = "sec-websocket-accept:";
        if (detail::istarts_with(line, kName)) {
            std::string_view val = line.substr(kName.size());
            // trim leading spaces
            while (!val.empty() && val.front() == ' ') {
                val.remove_prefix(1);
            }
            while (!val.empty() && val.back() == ' ') {
                val.remove_suffix(1);
            }
            r.accepted = (val == expected_accept_b64);
            return r;
        }
        pos = eol + 2;
    }
    return r;  // accept header missing
}

// ── REST client (order fallback) ─────────────────────────────────────────────

enum class HttpMethod : uint8_t { Get, Post, Delete, Put };

[[nodiscard]] inline std::string_view http_method_str(HttpMethod m) noexcept {
    switch (m) {
        case HttpMethod::Get:  return "GET";
        case HttpMethod::Post: return "POST";
        case HttpMethod::Delete:  return "DELETE";
        case HttpMethod::Put:  return "PUT";
    }
    return "GET";
}

/// Build a request (method, path, headers, optional body) into `dst`.
/// Caller supplies pre-formatted header lines WITHOUT trailing CRLF (e.g.
/// "X-MBX-APIKEY: ...", "Content-Type: application/json"); signing/JSON happen
/// in the connector layer, not here. A Host header and a Content-Length header
/// (when body is non-empty) are added automatically. Returns bytes written or 0
/// on overflow.
[[nodiscard]] inline std::size_t build_http_request(
    std::span<char> dst, HttpMethod method, std::string_view host, std::string_view path,
    std::span<std::string_view> header_lines, std::span<const uint8_t> body) noexcept {
    std::size_t o = 0;
    auto put = [&](std::string_view s) noexcept -> bool {
        if (o + s.size() > dst.size()) {
            return false;
        }
        std::memcpy(dst.data() + o, s.data(), s.size());
        o += s.size();
        return true;
    };

    if (!put(http_method_str(method)) || !put(" ") || !put(path) ||
        !put(" HTTP/1.1\r\nHost: ") || !put(host) || !put("\r\n")) {
        return 0;
    }
    for (std::string_view h : header_lines) {
        if (!put(h) || !put("\r\n")) {
            return 0;
        }
    }
    if (!body.empty()) {
        // Content-Length: <n>\r\n  (format the number without allocation)
        char num[24];
        std::size_t v = body.size();
        std::size_t p = sizeof(num);
        do {
            num[--p] = static_cast<char>('0' + (v % 10));
            v /= 10;
        } while (v != 0);
        if (!put("Content-Length: ") || !put({num + p, sizeof(num) - p}) || !put("\r\n")) {
            return 0;
        }
    }
    if (!put("\r\n")) {  // end of headers
        return 0;
    }
    if (!body.empty()) {
        if (o + body.size() > dst.size()) {
            return 0;
        }
        std::memcpy(dst.data() + o, body.data(), body.size());
        o += body.size();
    }
    return o;
}

struct HttpResponseView {
    bool complete{false};
    int status{0};
    std::span<const uint8_t> body;   ///< view into the response buffer; call-scoped
    std::size_t consumed{0};         ///< total bytes of this response (headers+body)
};

namespace detail {

/// Parse a hex chunk-size line. Returns SIZE_MAX on malformed input.
[[nodiscard]] inline std::size_t parse_hex(std::string_view s) noexcept {
    std::size_t v = 0;
    if (s.empty()) {
        return std::numeric_limits<std::size_t>::max();
    }
    for (char c : s) {
        int d;
        if (c >= '0' && c <= '9') {
            d = c - '0';
        } else if (c >= 'a' && c <= 'f') {
            d = c - 'a' + 10;
        } else if (c >= 'A' && c <= 'F') {
            d = c - 'A' + 10;
        } else if (c == ';') {
            break;  // chunk extension; ignore the rest
        } else {
            return std::numeric_limits<std::size_t>::max();
        }
        v = v * 16 + static_cast<std::size_t>(d);
    }
    return v;
}

} // namespace detail

/// Incrementally parse an HTTP/1.1 response buffer. Supports Content-Length and
/// chunked transfer-encoding. Returns complete=false until the full message is
/// present (caller keeps reading). The returned `body` is a view into `buf`
/// (valid only as long as `buf` is). For chunked bodies the body view is not
/// contiguous with the wire bytes, so the decoded body is written back into the
/// front of `buf` in place (safe: decoded length <= encoded length).
[[nodiscard]] inline HttpResponseView parse_http_response(std::span<uint8_t> buf) noexcept {
    HttpResponseView r;
    std::string_view s{reinterpret_cast<const char*>(buf.data()), buf.size()};

    const auto hdr_end = s.find("\r\n\r\n");
    if (hdr_end == std::string_view::npos) {
        return r;  // headers incomplete
    }
    const std::size_t body_start = hdr_end + 4;

    // Status line: "HTTP/1.x <code> ...".
    const auto sp = s.find(' ');
    if (sp == std::string_view::npos || sp + 4 > s.size()) {
        return r;
    }
    char c1 = s[sp + 1];
    char c2 = s[sp + 2];
    char c3 = s[sp + 3];
    if (c1 >= '0' && c1 <= '9' && c2 >= '0' && c2 <= '9' && c3 >= '0' && c3 <= '9') {
        r.status = (c1 - '0') * 100 + (c2 - '0') * 10 + (c3 - '0');
    } else {
        r.status = 502; // Bad Gateway / Invalid status from upstream
    }

    // Scan headers for Content-Length / Transfer-Encoding: chunked.
    std::string_view headers = s.substr(0, hdr_end + 2);  // include final CRLF
    bool chunked = false;
    std::size_t content_len = std::numeric_limits<std::size_t>::max();
    std::size_t pos = 0;
    while (pos < headers.size()) {
        std::size_t eol = headers.find("\r\n", pos);
        if (eol == std::string_view::npos) {
            break;
        }
        std::string_view line = headers.substr(pos, eol - pos);
        constexpr std::string_view kContentLength = "content-length:";
        constexpr std::string_view kTransferEncoding = "transfer-encoding:";
        if (detail::istarts_with(line, kContentLength)) {
            std::string_view v = line.substr(kContentLength.size());
            while (!v.empty() && v.front() == ' ') {
                v.remove_prefix(1);
            }
            std::size_t n = 0;
            for (char c : v) {
                if (c < '0' || c > '9') {
                    break;
                }
                n = n * 10 + static_cast<std::size_t>(c - '0');
            }
            content_len = n;
        } else if (detail::istarts_with(line, kTransferEncoding)) {
            std::string_view v = line.substr(kTransferEncoding.size());
            if (v.find("chunked") != std::string_view::npos) {
                chunked = true;
            }
        }
        pos = eol + 2;
    }

    if (!chunked) {
        if (content_len == std::numeric_limits<std::size_t>::max()) {
            content_len = 0;  // no body (typical for 204 / some errors)
        }
        if (buf.size() < body_start + content_len) {
            return r;  // body incomplete
        }
        r.complete = true;
        r.body = {buf.data() + body_start, content_len};
        r.consumed = body_start + content_len;
        return r;
    }

    // Dry run to check if all chunks are fully present before mutating the buffer.
    bool all_present = false;
    std::size_t dry_rp = body_start;
    for (;;) {
        std::size_t line_end = s.find("\r\n", dry_rp);
        if (line_end == std::string_view::npos) {
            break;
        }
        std::size_t chunk_sz = detail::parse_hex(s.substr(dry_rp, line_end - dry_rp));
        if (chunk_sz == std::numeric_limits<std::size_t>::max()) {
            all_present = true; // let actual run handle malformed error
            break;
        }
        std::size_t data_start = line_end + 2;
        if (chunk_sz == 0) {
            std::size_t term = s.find("\r\n\r\n", line_end);
            if (term == std::string_view::npos) {
                break;
            }
            all_present = true;
            break;
        }
        if (buf.size() < data_start + chunk_sz + 2) {
            break;
        }
        dry_rp = data_start + chunk_sz + 2;
    }

    if (!all_present) {
        return r;
    }

    // Chunked: decode in place into the region starting at body_start.
    std::size_t rp = body_start;                 // read cursor (encoded)
    std::size_t wp = body_start;                 // write cursor (decoded)
    for (;;) {
        std::size_t line_end = s.find("\r\n", rp);
        if (line_end == std::string_view::npos) {
            return r;  // need more bytes for the chunk-size line
        }
        std::size_t chunk_sz = detail::parse_hex(s.substr(rp, line_end - rp));
        if (chunk_sz == std::numeric_limits<std::size_t>::max()) {
            r.complete = true;  // malformed; surface what we have as a terminal error
            r.status = r.status ? r.status : 502;
            r.consumed = buf.size();
            return r;
        }
        std::size_t data_start = line_end + 2;
        if (chunk_sz == 0) {
            // Final chunk; expect a trailing CRLF after (optional trailers).
            std::size_t term = s.find("\r\n\r\n", line_end);
            if (term == std::string_view::npos) {
                return r;  // wait for terminator
            }
            r.complete = true;
            r.body = {buf.data() + body_start, wp - body_start};
            r.consumed = term + 4;
            return r;
        }
        if (buf.size() < data_start + chunk_sz + 2) {
            return r;  // chunk body (+ CRLF) not fully present
        }
        std::memmove(buf.data() + wp, buf.data() + data_start, chunk_sz);
        wp += chunk_sz;
        rp = data_start + chunk_sz + 2;  // skip chunk data + trailing CRLF
    }
}

} // namespace lepton::net
